/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import Clases.PlayWave;
import java.awt.Color;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;

/**
 *
 * @author Ashley
 */
public class FrmPrincipal extends javax.swing.JFrame {

    private JLabel[] tablero = new JLabel[16];          //Arreglo de etiquetas 
    private int[] datos = new int[16];                  // Areglo de datos para las etiquetas
    private int pos1;                                   
    private int pos2;
    private boolean banClick;
    private int tipo;                                   //0=libre, 1=tradicional
    private int disponible;                             //casilla vacia en tipo tradicional
    private JLabel lblTempo = new JLabel();
    private boolean banInicio;                          //true:ya inició el juego, 
    //false: aun no inicia el juego

     private Creditos acercaDe;
    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblImagen01 = new javax.swing.JLabel();
        lblImagen02 = new javax.swing.JLabel();
        lblImagen03 = new javax.swing.JLabel();
        lblImagen04 = new javax.swing.JLabel();
        lblImagen08 = new javax.swing.JLabel();
        lblImagen07 = new javax.swing.JLabel();
        lblImagen06 = new javax.swing.JLabel();
        lblImagen05 = new javax.swing.JLabel();
        lblImagen12 = new javax.swing.JLabel();
        lblImagen11 = new javax.swing.JLabel();
        lblImagen10 = new javax.swing.JLabel();
        lblImagen09 = new javax.swing.JLabel();
        lblImagen16 = new javax.swing.JLabel();
        lblImagen15 = new javax.swing.JLabel();
        lblImagen14 = new javax.swing.JLabel();
        lblImagen13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbImagenes = new javax.swing.JComboBox<>();
        btnMezclar = new javax.swing.JButton();
        btnCreditos = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        cmbTipo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 102, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImagen01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/g_01.jpg"))); // NOI18N
        lblImagen01.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImagen01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen01MouseClicked(evt);
            }
        });
        jPanel1.add(lblImagen01, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        lblImagen02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/g_02.jpg"))); // NOI18N
        lblImagen02.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImagen02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen02MouseClicked(evt);
            }
        });
        jPanel1.add(lblImagen02, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        lblImagen03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/g_03.jpg"))); // NOI18N
        lblImagen03.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImagen03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen03MouseClicked(evt);
            }
        });
        jPanel1.add(lblImagen03, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        lblImagen04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/g_04.jpg"))); // NOI18N
        lblImagen04.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImagen04.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen04MouseClicked(evt);
            }
        });
        jPanel1.add(lblImagen04, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, -1, -1));

        lblImagen08.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/g_08.jpg"))); // NOI18N
        lblImagen08.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImagen08.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen08MouseClicked(evt);
            }
        });
        jPanel1.add(lblImagen08, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, -1, -1));

        lblImagen07.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/g_07.jpg"))); // NOI18N
        lblImagen07.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImagen07.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen07MouseClicked(evt);
            }
        });
        jPanel1.add(lblImagen07, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, -1, -1));

        lblImagen06.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/g_06.jpg"))); // NOI18N
        lblImagen06.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImagen06.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen06MouseClicked(evt);
            }
        });
        jPanel1.add(lblImagen06, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, -1));

        lblImagen05.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/g_05.jpg"))); // NOI18N
        lblImagen05.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImagen05.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen05MouseClicked(evt);
            }
        });
        jPanel1.add(lblImagen05, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        lblImagen12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/g_12.jpg"))); // NOI18N
        lblImagen12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImagen12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen12MouseClicked(evt);
            }
        });
        jPanel1.add(lblImagen12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, -1, -1));

        lblImagen11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/g_11.jpg"))); // NOI18N
        lblImagen11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImagen11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen11MouseClicked(evt);
            }
        });
        jPanel1.add(lblImagen11, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, -1, -1));

        lblImagen10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/g_10.jpg"))); // NOI18N
        lblImagen10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImagen10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen10MouseClicked(evt);
            }
        });
        jPanel1.add(lblImagen10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, -1, -1));

        lblImagen09.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/g_09.jpg"))); // NOI18N
        lblImagen09.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImagen09.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen09MouseClicked(evt);
            }
        });
        jPanel1.add(lblImagen09, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        lblImagen16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/g_16.jpg"))); // NOI18N
        lblImagen16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImagen16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen16MouseClicked(evt);
            }
        });
        jPanel1.add(lblImagen16, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, -1, -1));

        lblImagen15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/g_15.jpg"))); // NOI18N
        lblImagen15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImagen15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen15MouseClicked(evt);
            }
        });
        jPanel1.add(lblImagen15, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, -1, -1));

        lblImagen14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/g_14.jpg"))); // NOI18N
        lblImagen14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImagen14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen14MouseClicked(evt);
            }
        });
        jPanel1.add(lblImagen14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, -1, -1));

        lblImagen13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/g_13.jpg"))); // NOI18N
        lblImagen13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImagen13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen13MouseClicked(evt);
            }
        });
        jPanel1.add(lblImagen13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 100, -1));

        jPanel2.setBackground(new java.awt.Color(255, 102, 51));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Imágenes:");

        cmbImagenes.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        cmbImagenes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Monkey", "The Beatles", "Rick and Morty", "Star Wars", "Lost Woods", "The Legend of Zelda" }));
        cmbImagenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbImagenesActionPerformed(evt);
            }
        });

        btnMezclar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnMezclar.setText("Mezclar");
        btnMezclar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMezclarActionPerformed(evt);
            }
        });

        btnCreditos.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnCreditos.setText("Créditos");
        btnCreditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreditosActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        cmbTipo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Libre", "Tradicional" }));
        cmbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tipo:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cmbTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(cmbImagenes, 0, 163, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMezclar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbImagenes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnMezclar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCreditos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        tablero[0] = lblImagen01;
        tablero[1] = lblImagen02;
        tablero[2] = lblImagen03;
        tablero[3] = lblImagen04;
        tablero[4] = lblImagen05;
        tablero[5] = lblImagen06;
        tablero[6] = lblImagen07;
        tablero[7] = lblImagen08;
        tablero[8] = lblImagen09;
        tablero[9] = lblImagen10;
        tablero[10] = lblImagen11;
        tablero[11] = lblImagen12;
        tablero[12] = lblImagen13;
        tablero[13] = lblImagen14;
        tablero[14] = lblImagen15;
        tablero[15] = lblImagen16;

        for (int i = 0; i < 16; i++) {
            datos[i] = i;
        }
        sonidoFondo();
    }//GEN-LAST:event_formWindowOpened
    /**
    * Metodo que le da funcionalidad al boton Mezclar.
    * @param evt 
    */
    private void btnMezclarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMezclarActionPerformed
        // TODO add your handling code here:
        Random r1 = new Random();
        int x;
        if (tipo == 0) {                        // modo libre
            for (int i = 1; i < 100; i++) {
                x = r1.nextInt(16);
                seleccionar(x);
            }
        } else if (tipo == 1) {                 //modo tradicional
            for (int i = 1; i <= 1000; i++) {
                x = r1.nextInt(16);
                mover(x);
            }
        }
        banInicio = true;
    }//GEN-LAST:event_btnMezclarActionPerformed
    /**
     * Metodos para poder seleccionar las casillas de las etiquetas
     * @param evt 
     */
    private void lblImagen01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen01MouseClicked
        // TODO add your handling code here:
        tirar(0);
    }//GEN-LAST:event_lblImagen01MouseClicked

    private void lblImagen02MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen02MouseClicked
        // TODO add your handling code here:
        tirar(1);
    }//GEN-LAST:event_lblImagen02MouseClicked

    private void lblImagen03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen03MouseClicked
        // TODO add your handling code here:
        tirar(2);
    }//GEN-LAST:event_lblImagen03MouseClicked

    private void lblImagen04MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen04MouseClicked
        // TODO add your handling code here:
        tirar(3);
    }//GEN-LAST:event_lblImagen04MouseClicked

    private void lblImagen05MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen05MouseClicked
        // TODO add your handling code here:
        tirar(4);
    }//GEN-LAST:event_lblImagen05MouseClicked

    private void lblImagen06MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen06MouseClicked
        // TODO add your handling code here:
        tirar(5);
    }//GEN-LAST:event_lblImagen06MouseClicked

    private void lblImagen07MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen07MouseClicked
        // TODO add your handling code here:
        tirar(6);
    }//GEN-LAST:event_lblImagen07MouseClicked

    private void lblImagen08MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen08MouseClicked
        // TODO add your handling code here:
        tirar(7);
    }//GEN-LAST:event_lblImagen08MouseClicked

    private void lblImagen09MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen09MouseClicked
        // TODO add your handling code here:
        tirar(8);
    }//GEN-LAST:event_lblImagen09MouseClicked

    private void lblImagen10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen10MouseClicked
        // TODO add your handling code here:
        tirar(9);
    }//GEN-LAST:event_lblImagen10MouseClicked

    private void lblImagen11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen11MouseClicked
        // TODO add your handling code here:
        tirar(10);
    }//GEN-LAST:event_lblImagen11MouseClicked

    private void lblImagen12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen12MouseClicked
        // TODO add your handling code here:
        tirar(11);
    }//GEN-LAST:event_lblImagen12MouseClicked

    private void lblImagen13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen13MouseClicked
        // TODO add your handling code here:
        tirar(12);
    }//GEN-LAST:event_lblImagen13MouseClicked

    private void lblImagen14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen14MouseClicked
        // TODO add your handling code here:
        tirar(13);
    }//GEN-LAST:event_lblImagen14MouseClicked

    private void lblImagen15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen15MouseClicked
        // TODO add your handling code here:
        tirar(14);
    }//GEN-LAST:event_lblImagen15MouseClicked

    private void lblImagen16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen16MouseClicked
        // TODO add your handling code here:
        tirar(15);
    }//GEN-LAST:event_lblImagen16MouseClicked
    /**
     * Metodo que le da funcionalidad al combobox Imagenes, y el
     * cual al seleccionar una categoria de imagenes cambia
     * las imagenes dependiendo la categoria escogida.
     * @param evt 
     */
    private void cmbImagenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbImagenesActionPerformed
        // TODO add your handling code here:
        banInicio = false;                                          //requiere mezclarse para iniciar
        disponible = 15;
        //se inicializan los datos
        for (int i = 0; i < 16; i++) {
            datos[i] = i;
        }
        //poniendo borde a las piezas del tablero
        for (int i = 0; i < 16; i++) {
            tablero[i].setBorder(new LineBorder(Color.black, 1));
        }
        int op;
        op = cmbImagenes.getSelectedIndex();
        switch (op) {
            case 0:                 // Imagenes principal (Monkey)
                tablero[0].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/g_01.jpg")));
                tablero[1].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/g_02.jpg")));
                tablero[2].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/g_03.jpg")));
                tablero[3].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/g_04.jpg")));
                tablero[4].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/g_05.jpg")));
                tablero[5].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/g_06.jpg")));
                tablero[6].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/g_07.jpg")));
                tablero[7].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/g_08.jpg")));
                tablero[8].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/g_09.jpg")));
                tablero[9].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/g_10.jpg")));
                tablero[10].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/g_11.jpg")));
                tablero[11].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/g_12.jpg")));
                tablero[12].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/g_13.jpg")));
                tablero[13].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/g_14.jpg")));
                tablero[14].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/g_15.jpg")));
                if (tipo == 0) {
                    tablero[15].setIcon(new ImageIcon(getClass().
                            getResource("/imagenes/g_16.jpg")));
                } else {
                    tablero[15].setIcon(new ImageIcon(getClass().
                            getResource("/imagenes/vacia.jpg")));
                }
                break;
            case 1:                     // Imagenes The Beatles
                tablero[0].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/l_01.jpg")));
                tablero[1].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/l_02.jpg")));
                tablero[2].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/l_03.jpg")));
                tablero[3].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/l_04.jpg")));
                tablero[4].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/l_05.jpg")));
                tablero[5].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/l_06.jpg")));
                tablero[6].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/l_07.jpg")));
                tablero[7].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/l_08.jpg")));
                tablero[8].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/l_09.jpg")));
                tablero[9].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/l_10.jpg")));
                tablero[10].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/l_11.jpg")));
                tablero[11].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/l_12.jpg")));
                tablero[12].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/l_13.jpg")));
                tablero[13].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/l_14.jpg")));
                tablero[14].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/l_15.jpg")));
                if (tipo == 0) {
                    tablero[15].setIcon(new ImageIcon(getClass().
                            getResource("/imagenes/l_16.jpg")));
                } else {
                    tablero[15].setIcon(new ImageIcon(getClass().
                            getResource("/imagenes/vacia.jpg")));
                }
                break;
            case 2:                     //Imagenes Rick and Morty
                tablero[0].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/r_01.jpg")));
                tablero[1].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/r_02.jpg")));
                tablero[2].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/r_03.jpg")));
                tablero[3].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/r_04.jpg")));
                tablero[4].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/r_05.jpg")));
                tablero[5].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/r_06.jpg")));
                tablero[6].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/r_07.jpg")));
                tablero[7].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/r_08.jpg")));
                tablero[8].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/r_09.jpg")));
                tablero[9].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/r_10.jpg")));
                tablero[10].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/r_11.jpg")));
                tablero[11].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/r_12.jpg")));
                tablero[12].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/r_13.jpg")));
                tablero[13].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/r_14.jpg")));
                tablero[14].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/r_15.jpg")));
                if (tipo == 0) {
                    tablero[15].setIcon(new ImageIcon(getClass().
                            getResource("/imagenes/r_16.jpg")));
                } else {
                    tablero[15].setIcon(new ImageIcon(getClass().
                            getResource("/imagenes/vacia.jpg")));
                }
                break;
            case 3:                     // Imagenes Star Wars
                tablero[0].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/s_01.jpg")));
                tablero[1].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/s_02.jpg")));
                tablero[2].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/s_03.jpg")));
                tablero[3].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/s_04.jpg")));
                tablero[4].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/s_05.jpg")));
                tablero[5].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/s_06.jpg")));
                tablero[6].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/s_07.jpg")));
                tablero[7].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/s_08.jpg")));
                tablero[8].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/s_09.jpg")));
                tablero[9].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/s_10.jpg")));
                tablero[10].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/s_11.jpg")));
                tablero[11].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/s_12.jpg")));
                tablero[12].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/s_13.jpg")));
                tablero[13].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/s_14.jpg")));
                tablero[14].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/s_15.jpg")));
                if (tipo == 0) {
                    tablero[15].setIcon(new ImageIcon(getClass().
                            getResource("/imagenes/s_16.jpg")));
                } else {
                    tablero[15].setIcon(new ImageIcon(getClass().
                            getResource("/imagenes/vacia.jpg")));
                }
                break;
            case 4:                     // Imagenes TLOZ Lost Woods
                tablero[0].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/t_01.jpg")));
                tablero[1].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/t_02.jpg")));
                tablero[2].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/t_03.jpg")));
                tablero[3].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/t_04.jpg")));
                tablero[4].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/t_05.jpg")));
                tablero[5].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/t_06.jpg")));
                tablero[6].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/t_07.jpg")));
                tablero[7].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/t_08.jpg")));
                tablero[8].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/t_09.jpg")));
                tablero[9].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/t_10.jpg")));
                tablero[10].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/t_11.jpg")));
                tablero[11].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/t_12.jpg")));
                tablero[12].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/t_13.jpg")));
                tablero[13].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/t_14.jpg")));
                tablero[14].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/t_15.jpg")));
                if (tipo == 0) {
                    tablero[15].setIcon(new ImageIcon(getClass().
                            getResource("/imagenes/t_16.jpg")));
                } else {
                    tablero[15].setIcon(new ImageIcon(getClass().
                            getResource("/imagenes/vacia.jpg")));
                }
                break;
            case 5:                     // Imagenes TLOZ take this
                tablero[0].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/z_01.jpg")));
                tablero[1].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/z_02.jpg")));
                tablero[2].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/z_03.jpg")));
                tablero[3].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/z_04.jpg")));
                tablero[4].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/z_05.jpg")));
                tablero[5].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/z_06.jpg")));
                tablero[6].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/z_07.jpg")));
                tablero[7].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/z_08.jpg")));
                tablero[8].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/z_09.jpg")));
                tablero[9].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/z_10.jpg")));
                tablero[10].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/z_11.jpg")));
                tablero[11].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/z_12.jpg")));
                tablero[12].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/z_13.jpg")));
                tablero[13].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/z_14.jpg")));
                tablero[14].setIcon(new ImageIcon(getClass().
                        getResource("/imagenes/z_15.jpg")));
                if (tipo == 0) {
                    tablero[15].setIcon(new ImageIcon(getClass().
                            getResource("/imagenes/z_16.jpg")));
                } else {
                    tablero[15].setIcon(new ImageIcon(getClass().
                            getResource("/imagenes/vacia.jpg")));
                }
                break;
        }
    }//GEN-LAST:event_cmbImagenesActionPerformed
    /**
     * Metodo para escoger el tipo de juego (Libre o Tradicional)
     * @param evt 
     */
    private void cmbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoActionPerformed
        // TODO add your handling code here:

        tipo = cmbTipo.getSelectedIndex();
        if (tipo == 0) {                //libre
            // ...
        } else if (tipo == 1) {         //Tradicional
            lblImagen16.setIcon(new ImageIcon(getClass().
                    getResource("/imagenes/vacia.jpg")));
            disponible = 15;
        }
        this.cmbImagenesActionPerformed(null);
    }//GEN-LAST:event_cmbTipoActionPerformed
    /**
     * Metodo para darle funcionalidad al boton Salir
     * @param evt 
     */
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed
    /**
     * Metodo que da funcionalidad al boton Creditos,
     * y muestra el formulario Creditos
     * @param evt 
     */
    private void btnCreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreditosActionPerformed
        // TODO add your handling code here:
        acercaDe = new Creditos();
        acercaDe.setVisible(true);              // Lo hace visible
    }//GEN-LAST:event_btnCreditosActionPerformed
    /**
     * Metodo que verifica si el movimiento que esta realizando es valido
     * @param pos
     * @return 
     */
    private boolean esValidoMov(int pos) {
        boolean salida = false;
        int dx;                 //Fila del disponible
        int dy;                 //Columna del disponible
        int posx;               //fila de posicion a vereficar
        int posy;               //columna de posicion a verificar
        dx = disponible / 4;    
        dy = disponible % 4;
        posx = pos / 4;
        posy = pos % 4;
        if (dx == posx) { //misma fila
            if (Math.abs(disponible - pos) == 1) {
                salida = true;
            }
        }
        if (dy == posy) { //misma columna
            if (Math.abs(disponible - pos) == 4) {
                salida = true;
            }
        }
        return salida;
    }
    /**
     * Metodo para seleccionar casillas
     * @param pos 
     */
    private void seleccionar(int pos) {
        if (!banClick) {    //primer click
            pos1 = pos;
            tablero[pos1].setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 1));
            banClick = true;
        } else {
            pos2 = pos;
            tablero[pos1].setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 1));
            banClick = false;
            intercambiar(pos1, pos2);
        }

    }
    /**
     * Metodo para intercambiar casillas de
     * posicion con otra casilla seleccionada
     * @param pos1
     * @param pos2 
     */
    private void intercambiar(int pos1, int pos2) {
        //Intercambio de imagenes de la posición
        JLabel lblTempo = new JLabel();
        lblTempo.setIcon(tablero[pos1].getIcon());
        tablero[pos1].setIcon(tablero[pos2].getIcon());
        tablero[pos2].setIcon(lblTempo.getIcon());
        int tempo;
        tempo = datos[pos1];
        datos[pos1] = datos[pos2];
        datos[pos2] = tempo;
    }
    /**
     * Metodo para revisar si ya se gano el juego
     */
    private void revisar() {
        if (banInicio && !banClick && verificar()) {
            JOptionPane.showMessageDialog(this, "Ya ganaste!");
            //banPlay= false;
            for (int i = 0; i < 16; i++) {
                tablero[i].setBorder(null);
            }
            banInicio = false;
        }
    }

    /**
     * Verifica si ya ganó, es decir si el rompecabezas ya esta armado
     * correctamente.
     *
     * @return true= ya ganó, false= no ha ganado.
     */
    private boolean verificar() {
        for (int i = 0; i < 16; i++) {
            if (datos[i] != i) {
                return false;
            }
        }
        return true;
    }
    /**
     * Metodo para mover las imagenes en el modo libre
     * @param pos 
     */
    public void mover(int pos) {
        if (banInicio) {
            if (tipo == 0) {
                seleccionar(pos);
            } else if (tipo == 1) {
                if (esValidoMov(pos)) {
                    intercambiar(pos, disponible);
                    disponible = pos;
                }
            }
        }
    }
    /**
     * Metodo para mover toda una linea en el metodo tradicional
     * @param pos 
     */
    private void moverLinea(int pos) {
        if (banInicio) {
//            if (tipo == 2) {
//                lblTempo.setIcon(tablero[0].getIcon());
//                disponible = 0;
//                pos = 12;
//            }
            if (pos / 4 == disponible / 4) { //pertenecen a la misma fila
                if (pos > disponible) { //esta a la derecha
                    for (int i = disponible + 1; i <= pos; i++) {
                        mover(i);
                    }
                } else {
                    for (int i = disponible - 1; i >= pos; i--) {
                        mover(i);
                    }

                }
            } else if (pos % 4 == disponible % 4) {// misma columna
                if (pos > disponible) {// esta abajo 
                    for (int i = disponible + 4; i <= pos; i = i + 4) {
                        mover(i);
                    }
                } else {
                    for (int i = disponible - 4; i >= pos; i = i - 4) {
                        mover(i);
                    }
                }
            }
        }
    }
    /**
     * Metodo para poder tirar, dependiendo del modo (Libre o Tradicional)
     * @param pos 
     */
    public void tirar(int pos) {
        if (tipo == 0) {
            mover(pos);
        } else if (tipo == 1) {
            moverLinea(pos);
        }
        revisar();
    }
    /**
     * Metodo para poder reproducir dulces melodias musicales!!!
     */
     public void sonidoFondo() {
        try {
            PlayWave pw1;
            URL ur1 = getClass().getResource("/mediaP/Song2.wav");
            pw1 = new PlayWave(ur1);
            pw1.start();
        } catch (URISyntaxException e) {
            System.out.println(" Error en la URL!! ");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreditos;
    private javax.swing.JButton btnMezclar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cmbImagenes;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblImagen01;
    private javax.swing.JLabel lblImagen02;
    private javax.swing.JLabel lblImagen03;
    private javax.swing.JLabel lblImagen04;
    private javax.swing.JLabel lblImagen05;
    private javax.swing.JLabel lblImagen06;
    private javax.swing.JLabel lblImagen07;
    private javax.swing.JLabel lblImagen08;
    private javax.swing.JLabel lblImagen09;
    private javax.swing.JLabel lblImagen10;
    private javax.swing.JLabel lblImagen11;
    private javax.swing.JLabel lblImagen12;
    private javax.swing.JLabel lblImagen13;
    private javax.swing.JLabel lblImagen14;
    private javax.swing.JLabel lblImagen15;
    private javax.swing.JLabel lblImagen16;
    // End of variables declaration//GEN-END:variables
}
